// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Comm.proto

package drive_protocol;

public final class Comm {
  private Comm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_drive_protocol_comm_ConnectionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_drive_protocol_comm_ConnectionInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nComm.proto\022\023drive_protocol.comm\"I\n\016Con" +
      "nectionInfo\022\022\n\nmachine_id\030\001 \001(\t\022\017\n\007user_" +
      "id\030\002 \001(\t\022\022\n\nsession_id\030\003 \001(\t*\"\n\007Command\022" +
      "\r\n\tHandshake\020\000\022\010\n\004Test\020\001B\022\n\016drive_protoc" +
      "olP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_drive_protocol_comm_ConnectionInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_drive_protocol_comm_ConnectionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_drive_protocol_comm_ConnectionInfo_descriptor,
        new java.lang.String[] { "MachineId", "UserId", "SessionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
