// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DriveProcedure.proto

package drive_protocol;

public final class DriveProcedureOuterClass {
  private DriveProcedureOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024DriveProcedure.proto\022\016drive_protocol\032\r" +
      "Request.proto\032\016Response.proto2\216\014\n\016DriveP" +
      "rocedure\022f\n\nCreateFile\022).drive_protocol." +
      "request.CreateFileRequest\032+.drive_protoc" +
      "ol.response.CreateFileResponse\"\000\022c\n\tClos" +
      "eFile\022(.drive_protocol.request.CloseFile" +
      "Request\032*.drive_protocol.response.CloseF" +
      "ileResponse\"\000\022`\n\010ReadFile\022\'.drive_protoc" +
      "ol.request.ReadFileRequest\032).drive_proto" +
      "col.response.ReadFileResponse\"\000\022c\n\tWrite" +
      "File\022(.drive_protocol.request.WriteFileR" +
      "equest\032*.drive_protocol.response.WriteFi" +
      "leResponse\"\000\022u\n\017FlushFileBuffer\022..drive_" +
      "protocol.request.FlushFileBufferRequest\032" +
      "0.drive_protocol.response.FlushFileBuffe" +
      "rResponse\"\000\022~\n\022GetFileInformation\0221.driv" +
      "e_protocol.request.GetFileInformationReq" +
      "uest\0323.drive_protocol.response.GetFileIn" +
      "formationResponse\"\000\022f\n\nDeleteFile\022).driv" +
      "e_protocol.request.DeleteFileRequest\032+.d" +
      "rive_protocol.response.DeleteFileRespons" +
      "e\"\000\022u\n\017DeleteDirectory\022..drive_protocol." +
      "request.DeleteDirectoryRequest\0320.drive_p" +
      "rotocol.response.DeleteDirectoryResponse" +
      "\"\000\022`\n\010MoveFile\022\'.drive_protocol.request." +
      "MoveFileRequest\032).drive_protocol.respons" +
      "e.MoveFileResponse\"\000\022`\n\010LockFile\022\'.drive" +
      "_protocol.request.LockFileRequest\032).driv" +
      "e_protocol.response.LockFileResponse\"\000\022l" +
      "\n\014SetEndOfFile\022+.drive_protocol.request." +
      "SetEndOfFileRequest\032-.drive_protocol.res" +
      "ponse.SetEndOfFileResponse\"\000\022{\n\021SetAlloc" +
      "ationSize\0220.drive_protocol.request.SetAl" +
      "locationSizeRequest\0322.drive_protocol.res" +
      "ponse.SetAllocationSizeResponse\"\000\022{\n\021Set" +
      "FileAttributes\0220.drive_protocol.request." +
      "SetFileAttributesRequest\0322.drive_protoco" +
      "l.response.SetFileAttributesResponse\"\000\022f" +
      "\n\nUnlockFile\022).drive_protocol.request.Un" +
      "lockFileRequest\032+.drive_protocol.respons" +
      "e.UnlockFileResponse\"\000B\022\n\016drive_protocol" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          drive_protocol.request.Request.getDescriptor(),
          drive_protocol.response.Response.getDescriptor(),
        });
    drive_protocol.request.Request.getDescriptor();
    drive_protocol.response.Response.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
