// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Model.proto

package drive_protocol.response;

public interface SetEndOfFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:drive_protocol.response.SetEndOfFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 status = 1;</code>
   * @return The status.
   */
  long getStatus();
}
