// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Model.proto

package drive_protocol.request;

public interface RequestInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:drive_protocol.request.RequestInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 process_id = 1;</code>
   * @return The processId.
   */
  long getProcessId();

  /**
   * <code>bool is_directory = 2;</code>
   * @return The isDirectory.
   */
  boolean getIsDirectory();

  /**
   * <code>bool delete_on_close = 3;</code>
   * @return The deleteOnClose.
   */
  boolean getDeleteOnClose();

  /**
   * <code>bool paging_io = 4;</code>
   * @return The pagingIo.
   */
  boolean getPagingIo();

  /**
   * <code>bool synchronous_io = 5;</code>
   * @return The synchronousIo.
   */
  boolean getSynchronousIo();

  /**
   * <code>bool no_cache = 6;</code>
   * @return The noCache.
   */
  boolean getNoCache();

  /**
   * <code>bool write_to_end_of_file = 7;</code>
   * @return The writeToEndOfFile.
   */
  boolean getWriteToEndOfFile();
}
