// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Model.proto

package drive_protocol.request;

/**
 * Protobuf type {@code drive_protocol.request.RequestInfo}
 */
public final class RequestInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:drive_protocol.request.RequestInfo)
    RequestInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestInfo.newBuilder() to construct.
  private RequestInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestInfo() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            processId_ = input.readUInt64();
            break;
          }
          case 16: {

            isDirectory_ = input.readBool();
            break;
          }
          case 24: {

            deleteOnClose_ = input.readBool();
            break;
          }
          case 32: {

            pagingIo_ = input.readBool();
            break;
          }
          case 40: {

            synchronousIo_ = input.readBool();
            break;
          }
          case 48: {

            noCache_ = input.readBool();
            break;
          }
          case 56: {

            writeToEndOfFile_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return drive_protocol.request.Model.internal_static_drive_protocol_request_RequestInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return drive_protocol.request.Model.internal_static_drive_protocol_request_RequestInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            drive_protocol.request.RequestInfo.class, drive_protocol.request.RequestInfo.Builder.class);
  }

  public static final int PROCESS_ID_FIELD_NUMBER = 1;
  private long processId_;
  /**
   * <code>uint64 process_id = 1;</code>
   * @return The processId.
   */
  @java.lang.Override
  public long getProcessId() {
    return processId_;
  }

  public static final int IS_DIRECTORY_FIELD_NUMBER = 2;
  private boolean isDirectory_;
  /**
   * <code>bool is_directory = 2;</code>
   * @return The isDirectory.
   */
  @java.lang.Override
  public boolean getIsDirectory() {
    return isDirectory_;
  }

  public static final int DELETE_ON_CLOSE_FIELD_NUMBER = 3;
  private boolean deleteOnClose_;
  /**
   * <code>bool delete_on_close = 3;</code>
   * @return The deleteOnClose.
   */
  @java.lang.Override
  public boolean getDeleteOnClose() {
    return deleteOnClose_;
  }

  public static final int PAGING_IO_FIELD_NUMBER = 4;
  private boolean pagingIo_;
  /**
   * <code>bool paging_io = 4;</code>
   * @return The pagingIo.
   */
  @java.lang.Override
  public boolean getPagingIo() {
    return pagingIo_;
  }

  public static final int SYNCHRONOUS_IO_FIELD_NUMBER = 5;
  private boolean synchronousIo_;
  /**
   * <code>bool synchronous_io = 5;</code>
   * @return The synchronousIo.
   */
  @java.lang.Override
  public boolean getSynchronousIo() {
    return synchronousIo_;
  }

  public static final int NO_CACHE_FIELD_NUMBER = 6;
  private boolean noCache_;
  /**
   * <code>bool no_cache = 6;</code>
   * @return The noCache.
   */
  @java.lang.Override
  public boolean getNoCache() {
    return noCache_;
  }

  public static final int WRITE_TO_END_OF_FILE_FIELD_NUMBER = 7;
  private boolean writeToEndOfFile_;
  /**
   * <code>bool write_to_end_of_file = 7;</code>
   * @return The writeToEndOfFile.
   */
  @java.lang.Override
  public boolean getWriteToEndOfFile() {
    return writeToEndOfFile_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (processId_ != 0L) {
      output.writeUInt64(1, processId_);
    }
    if (isDirectory_ != false) {
      output.writeBool(2, isDirectory_);
    }
    if (deleteOnClose_ != false) {
      output.writeBool(3, deleteOnClose_);
    }
    if (pagingIo_ != false) {
      output.writeBool(4, pagingIo_);
    }
    if (synchronousIo_ != false) {
      output.writeBool(5, synchronousIo_);
    }
    if (noCache_ != false) {
      output.writeBool(6, noCache_);
    }
    if (writeToEndOfFile_ != false) {
      output.writeBool(7, writeToEndOfFile_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (processId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, processId_);
    }
    if (isDirectory_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isDirectory_);
    }
    if (deleteOnClose_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, deleteOnClose_);
    }
    if (pagingIo_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, pagingIo_);
    }
    if (synchronousIo_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, synchronousIo_);
    }
    if (noCache_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, noCache_);
    }
    if (writeToEndOfFile_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, writeToEndOfFile_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof drive_protocol.request.RequestInfo)) {
      return super.equals(obj);
    }
    drive_protocol.request.RequestInfo other = (drive_protocol.request.RequestInfo) obj;

    if (getProcessId()
        != other.getProcessId()) return false;
    if (getIsDirectory()
        != other.getIsDirectory()) return false;
    if (getDeleteOnClose()
        != other.getDeleteOnClose()) return false;
    if (getPagingIo()
        != other.getPagingIo()) return false;
    if (getSynchronousIo()
        != other.getSynchronousIo()) return false;
    if (getNoCache()
        != other.getNoCache()) return false;
    if (getWriteToEndOfFile()
        != other.getWriteToEndOfFile()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROCESS_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProcessId());
    hash = (37 * hash) + IS_DIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDirectory());
    hash = (37 * hash) + DELETE_ON_CLOSE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDeleteOnClose());
    hash = (37 * hash) + PAGING_IO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPagingIo());
    hash = (37 * hash) + SYNCHRONOUS_IO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSynchronousIo());
    hash = (37 * hash) + NO_CACHE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNoCache());
    hash = (37 * hash) + WRITE_TO_END_OF_FILE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWriteToEndOfFile());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static drive_protocol.request.RequestInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static drive_protocol.request.RequestInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static drive_protocol.request.RequestInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static drive_protocol.request.RequestInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static drive_protocol.request.RequestInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static drive_protocol.request.RequestInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static drive_protocol.request.RequestInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static drive_protocol.request.RequestInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static drive_protocol.request.RequestInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static drive_protocol.request.RequestInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static drive_protocol.request.RequestInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static drive_protocol.request.RequestInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(drive_protocol.request.RequestInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code drive_protocol.request.RequestInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:drive_protocol.request.RequestInfo)
      drive_protocol.request.RequestInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drive_protocol.request.Model.internal_static_drive_protocol_request_RequestInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drive_protocol.request.Model.internal_static_drive_protocol_request_RequestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drive_protocol.request.RequestInfo.class, drive_protocol.request.RequestInfo.Builder.class);
    }

    // Construct using drive_protocol.request.RequestInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      processId_ = 0L;

      isDirectory_ = false;

      deleteOnClose_ = false;

      pagingIo_ = false;

      synchronousIo_ = false;

      noCache_ = false;

      writeToEndOfFile_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return drive_protocol.request.Model.internal_static_drive_protocol_request_RequestInfo_descriptor;
    }

    @java.lang.Override
    public drive_protocol.request.RequestInfo getDefaultInstanceForType() {
      return drive_protocol.request.RequestInfo.getDefaultInstance();
    }

    @java.lang.Override
    public drive_protocol.request.RequestInfo build() {
      drive_protocol.request.RequestInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public drive_protocol.request.RequestInfo buildPartial() {
      drive_protocol.request.RequestInfo result = new drive_protocol.request.RequestInfo(this);
      result.processId_ = processId_;
      result.isDirectory_ = isDirectory_;
      result.deleteOnClose_ = deleteOnClose_;
      result.pagingIo_ = pagingIo_;
      result.synchronousIo_ = synchronousIo_;
      result.noCache_ = noCache_;
      result.writeToEndOfFile_ = writeToEndOfFile_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof drive_protocol.request.RequestInfo) {
        return mergeFrom((drive_protocol.request.RequestInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(drive_protocol.request.RequestInfo other) {
      if (other == drive_protocol.request.RequestInfo.getDefaultInstance()) return this;
      if (other.getProcessId() != 0L) {
        setProcessId(other.getProcessId());
      }
      if (other.getIsDirectory() != false) {
        setIsDirectory(other.getIsDirectory());
      }
      if (other.getDeleteOnClose() != false) {
        setDeleteOnClose(other.getDeleteOnClose());
      }
      if (other.getPagingIo() != false) {
        setPagingIo(other.getPagingIo());
      }
      if (other.getSynchronousIo() != false) {
        setSynchronousIo(other.getSynchronousIo());
      }
      if (other.getNoCache() != false) {
        setNoCache(other.getNoCache());
      }
      if (other.getWriteToEndOfFile() != false) {
        setWriteToEndOfFile(other.getWriteToEndOfFile());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      drive_protocol.request.RequestInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (drive_protocol.request.RequestInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long processId_ ;
    /**
     * <code>uint64 process_id = 1;</code>
     * @return The processId.
     */
    @java.lang.Override
    public long getProcessId() {
      return processId_;
    }
    /**
     * <code>uint64 process_id = 1;</code>
     * @param value The processId to set.
     * @return This builder for chaining.
     */
    public Builder setProcessId(long value) {
      
      processId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 process_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessId() {
      
      processId_ = 0L;
      onChanged();
      return this;
    }

    private boolean isDirectory_ ;
    /**
     * <code>bool is_directory = 2;</code>
     * @return The isDirectory.
     */
    @java.lang.Override
    public boolean getIsDirectory() {
      return isDirectory_;
    }
    /**
     * <code>bool is_directory = 2;</code>
     * @param value The isDirectory to set.
     * @return This builder for chaining.
     */
    public Builder setIsDirectory(boolean value) {
      
      isDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_directory = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDirectory() {
      
      isDirectory_ = false;
      onChanged();
      return this;
    }

    private boolean deleteOnClose_ ;
    /**
     * <code>bool delete_on_close = 3;</code>
     * @return The deleteOnClose.
     */
    @java.lang.Override
    public boolean getDeleteOnClose() {
      return deleteOnClose_;
    }
    /**
     * <code>bool delete_on_close = 3;</code>
     * @param value The deleteOnClose to set.
     * @return This builder for chaining.
     */
    public Builder setDeleteOnClose(boolean value) {
      
      deleteOnClose_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool delete_on_close = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeleteOnClose() {
      
      deleteOnClose_ = false;
      onChanged();
      return this;
    }

    private boolean pagingIo_ ;
    /**
     * <code>bool paging_io = 4;</code>
     * @return The pagingIo.
     */
    @java.lang.Override
    public boolean getPagingIo() {
      return pagingIo_;
    }
    /**
     * <code>bool paging_io = 4;</code>
     * @param value The pagingIo to set.
     * @return This builder for chaining.
     */
    public Builder setPagingIo(boolean value) {
      
      pagingIo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool paging_io = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPagingIo() {
      
      pagingIo_ = false;
      onChanged();
      return this;
    }

    private boolean synchronousIo_ ;
    /**
     * <code>bool synchronous_io = 5;</code>
     * @return The synchronousIo.
     */
    @java.lang.Override
    public boolean getSynchronousIo() {
      return synchronousIo_;
    }
    /**
     * <code>bool synchronous_io = 5;</code>
     * @param value The synchronousIo to set.
     * @return This builder for chaining.
     */
    public Builder setSynchronousIo(boolean value) {
      
      synchronousIo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool synchronous_io = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSynchronousIo() {
      
      synchronousIo_ = false;
      onChanged();
      return this;
    }

    private boolean noCache_ ;
    /**
     * <code>bool no_cache = 6;</code>
     * @return The noCache.
     */
    @java.lang.Override
    public boolean getNoCache() {
      return noCache_;
    }
    /**
     * <code>bool no_cache = 6;</code>
     * @param value The noCache to set.
     * @return This builder for chaining.
     */
    public Builder setNoCache(boolean value) {
      
      noCache_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool no_cache = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoCache() {
      
      noCache_ = false;
      onChanged();
      return this;
    }

    private boolean writeToEndOfFile_ ;
    /**
     * <code>bool write_to_end_of_file = 7;</code>
     * @return The writeToEndOfFile.
     */
    @java.lang.Override
    public boolean getWriteToEndOfFile() {
      return writeToEndOfFile_;
    }
    /**
     * <code>bool write_to_end_of_file = 7;</code>
     * @param value The writeToEndOfFile to set.
     * @return This builder for chaining.
     */
    public Builder setWriteToEndOfFile(boolean value) {
      
      writeToEndOfFile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool write_to_end_of_file = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWriteToEndOfFile() {
      
      writeToEndOfFile_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:drive_protocol.request.RequestInfo)
  }

  // @@protoc_insertion_point(class_scope:drive_protocol.request.RequestInfo)
  private static final drive_protocol.request.RequestInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new drive_protocol.request.RequestInfo();
  }

  public static drive_protocol.request.RequestInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestInfo>
      PARSER = new com.google.protobuf.AbstractParser<RequestInfo>() {
    @java.lang.Override
    public RequestInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public drive_protocol.request.RequestInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

