// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DriveProcedure.proto

package drive_protocol;

public final class DriveProcedureOuterClass {
  private DriveProcedureOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024DriveProcedure.proto\022\016drive_protocol\032\023" +
      "request/Model.proto\032\024response/Model.prot" +
      "o2\216\014\n\016DriveProcedure\022f\n\nCreateFile\022).dri" +
      "ve_protocol.request.CreateFileRequest\032+." +
      "drive_protocol.response.CreateFileRespon" +
      "se\"\000\022c\n\tCloseFile\022(.drive_protocol.reque" +
      "st.CloseFileRequest\032*.drive_protocol.res" +
      "ponse.CloseFileResponse\"\000\022`\n\010ReadFile\022\'." +
      "drive_protocol.request.ReadFileRequest\032)" +
      ".drive_protocol.response.ReadFileRespons" +
      "e\"\000\022c\n\tWriteFile\022(.drive_protocol.reques" +
      "t.WriteFileRequest\032*.drive_protocol.resp" +
      "onse.WriteFileResponse\"\000\022u\n\017FlushFileBuf" +
      "fer\022..drive_protocol.request.FlushFileBu" +
      "fferRequest\0320.drive_protocol.response.Fl" +
      "ushFileBufferResponse\"\000\022~\n\022GetFileInform" +
      "ation\0221.drive_protocol.request.GetFileIn" +
      "formationRequest\0323.drive_protocol.respon" +
      "se.GetFileInformationResponse\"\000\022f\n\nDelet" +
      "eFile\022).drive_protocol.request.DeleteFil" +
      "eRequest\032+.drive_protocol.response.Delet" +
      "eFileResponse\"\000\022u\n\017DeleteDirectory\022..dri" +
      "ve_protocol.request.DeleteDirectoryReque" +
      "st\0320.drive_protocol.response.DeleteDirec" +
      "toryResponse\"\000\022`\n\010MoveFile\022\'.drive_proto" +
      "col.request.MoveFileRequest\032).drive_prot" +
      "ocol.response.MoveFileResponse\"\000\022`\n\010Lock" +
      "File\022\'.drive_protocol.request.LockFileRe" +
      "quest\032).drive_protocol.response.LockFile" +
      "Response\"\000\022l\n\014SetEndOfFile\022+.drive_proto" +
      "col.request.SetEndOfFileRequest\032-.drive_" +
      "protocol.response.SetEndOfFileResponse\"\000" +
      "\022{\n\021SetAllocationSize\0220.drive_protocol.r" +
      "equest.SetAllocationSizeRequest\0322.drive_" +
      "protocol.response.SetAllocationSizeRespo" +
      "nse\"\000\022{\n\021SetFileAttributes\0220.drive_proto" +
      "col.request.SetFileAttributesRequest\0322.d" +
      "rive_protocol.response.SetFileAttributes" +
      "Response\"\000\022f\n\nUnlockFile\022).drive_protoco" +
      "l.request.UnlockFileRequest\032+.drive_prot" +
      "ocol.response.UnlockFileResponse\"\000B\022\n\016dr" +
      "ive_protocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          drive_protocol.request.Model.getDescriptor(),
          drive_protocol.response.Model.getDescriptor(),
        });
    drive_protocol.request.Model.getDescriptor();
    drive_protocol.response.Model.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
