// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package drive_protocol.request;

/**
 * Protobuf type {@code drive_protocol.request.SubMessage}
 */
public final class SubMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:drive_protocol.request.SubMessage)
    SubMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubMessage.newBuilder() to construct.
  private SubMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubMessage() {
    command_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SubMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            drive_protocol.request.CredentialInfo.Builder subBuilder = null;
            if (cred_ != null) {
              subBuilder = cred_.toBuilder();
            }
            cred_ = input.readMessage(drive_protocol.request.CredentialInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cred_);
              cred_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            drive_protocol.request.SubMessage.class, drive_protocol.request.SubMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code drive_protocol.request.SubMessage.Command}
   */
  public enum Command
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Handshake = 0;</code>
     */
    Handshake(0),
    /**
     * <code>Test = 1;</code>
     */
    Test(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Handshake = 0;</code>
     */
    public static final int Handshake_VALUE = 0;
    /**
     * <code>Test = 1;</code>
     */
    public static final int Test_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Command valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Command forNumber(int value) {
      switch (value) {
        case 0: return Handshake;
        case 1: return Test;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Command>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Command> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Command>() {
            public Command findValueByNumber(int number) {
              return Command.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return drive_protocol.request.SubMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Command[] VALUES = values();

    public static Command valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Command(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:drive_protocol.request.SubMessage.Command)
  }

  public static final int CRED_FIELD_NUMBER = 1;
  private drive_protocol.request.CredentialInfo cred_;
  /**
   * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
   * @return Whether the cred field is set.
   */
  @java.lang.Override
  public boolean hasCred() {
    return cred_ != null;
  }
  /**
   * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
   * @return The cred.
   */
  @java.lang.Override
  public drive_protocol.request.CredentialInfo getCred() {
    return cred_ == null ? drive_protocol.request.CredentialInfo.getDefaultInstance() : cred_;
  }
  /**
   * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
   */
  @java.lang.Override
  public drive_protocol.request.CredentialInfoOrBuilder getCredOrBuilder() {
    return getCred();
  }

  public static final int COMMAND_FIELD_NUMBER = 2;
  private int command_;
  /**
   * <code>.drive_protocol.request.SubMessage.Command command = 2;</code>
   * @return The enum numeric value on the wire for command.
   */
  @java.lang.Override public int getCommandValue() {
    return command_;
  }
  /**
   * <code>.drive_protocol.request.SubMessage.Command command = 2;</code>
   * @return The command.
   */
  @java.lang.Override public drive_protocol.request.SubMessage.Command getCommand() {
    @SuppressWarnings("deprecation")
    drive_protocol.request.SubMessage.Command result = drive_protocol.request.SubMessage.Command.valueOf(command_);
    return result == null ? drive_protocol.request.SubMessage.Command.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cred_ != null) {
      output.writeMessage(1, getCred());
    }
    if (command_ != drive_protocol.request.SubMessage.Command.Handshake.getNumber()) {
      output.writeEnum(2, command_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cred_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCred());
    }
    if (command_ != drive_protocol.request.SubMessage.Command.Handshake.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, command_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof drive_protocol.request.SubMessage)) {
      return super.equals(obj);
    }
    drive_protocol.request.SubMessage other = (drive_protocol.request.SubMessage) obj;

    if (hasCred() != other.hasCred()) return false;
    if (hasCred()) {
      if (!getCred()
          .equals(other.getCred())) return false;
    }
    if (command_ != other.command_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCred()) {
      hash = (37 * hash) + CRED_FIELD_NUMBER;
      hash = (53 * hash) + getCred().hashCode();
    }
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static drive_protocol.request.SubMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static drive_protocol.request.SubMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(drive_protocol.request.SubMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code drive_protocol.request.SubMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:drive_protocol.request.SubMessage)
      drive_protocol.request.SubMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drive_protocol.request.SubMessage.class, drive_protocol.request.SubMessage.Builder.class);
    }

    // Construct using drive_protocol.request.SubMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (credBuilder_ == null) {
        cred_ = null;
      } else {
        cred_ = null;
        credBuilder_ = null;
      }
      command_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_descriptor;
    }

    @java.lang.Override
    public drive_protocol.request.SubMessage getDefaultInstanceForType() {
      return drive_protocol.request.SubMessage.getDefaultInstance();
    }

    @java.lang.Override
    public drive_protocol.request.SubMessage build() {
      drive_protocol.request.SubMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public drive_protocol.request.SubMessage buildPartial() {
      drive_protocol.request.SubMessage result = new drive_protocol.request.SubMessage(this);
      if (credBuilder_ == null) {
        result.cred_ = cred_;
      } else {
        result.cred_ = credBuilder_.build();
      }
      result.command_ = command_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof drive_protocol.request.SubMessage) {
        return mergeFrom((drive_protocol.request.SubMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(drive_protocol.request.SubMessage other) {
      if (other == drive_protocol.request.SubMessage.getDefaultInstance()) return this;
      if (other.hasCred()) {
        mergeCred(other.getCred());
      }
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      drive_protocol.request.SubMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (drive_protocol.request.SubMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private drive_protocol.request.CredentialInfo cred_;
    private com.google.protobuf.SingleFieldBuilderV3<
        drive_protocol.request.CredentialInfo, drive_protocol.request.CredentialInfo.Builder, drive_protocol.request.CredentialInfoOrBuilder> credBuilder_;
    /**
     * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
     * @return Whether the cred field is set.
     */
    public boolean hasCred() {
      return credBuilder_ != null || cred_ != null;
    }
    /**
     * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
     * @return The cred.
     */
    public drive_protocol.request.CredentialInfo getCred() {
      if (credBuilder_ == null) {
        return cred_ == null ? drive_protocol.request.CredentialInfo.getDefaultInstance() : cred_;
      } else {
        return credBuilder_.getMessage();
      }
    }
    /**
     * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
     */
    public Builder setCred(drive_protocol.request.CredentialInfo value) {
      if (credBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cred_ = value;
        onChanged();
      } else {
        credBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
     */
    public Builder setCred(
        drive_protocol.request.CredentialInfo.Builder builderForValue) {
      if (credBuilder_ == null) {
        cred_ = builderForValue.build();
        onChanged();
      } else {
        credBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
     */
    public Builder mergeCred(drive_protocol.request.CredentialInfo value) {
      if (credBuilder_ == null) {
        if (cred_ != null) {
          cred_ =
            drive_protocol.request.CredentialInfo.newBuilder(cred_).mergeFrom(value).buildPartial();
        } else {
          cred_ = value;
        }
        onChanged();
      } else {
        credBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
     */
    public Builder clearCred() {
      if (credBuilder_ == null) {
        cred_ = null;
        onChanged();
      } else {
        cred_ = null;
        credBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
     */
    public drive_protocol.request.CredentialInfo.Builder getCredBuilder() {
      
      onChanged();
      return getCredFieldBuilder().getBuilder();
    }
    /**
     * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
     */
    public drive_protocol.request.CredentialInfoOrBuilder getCredOrBuilder() {
      if (credBuilder_ != null) {
        return credBuilder_.getMessageOrBuilder();
      } else {
        return cred_ == null ?
            drive_protocol.request.CredentialInfo.getDefaultInstance() : cred_;
      }
    }
    /**
     * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        drive_protocol.request.CredentialInfo, drive_protocol.request.CredentialInfo.Builder, drive_protocol.request.CredentialInfoOrBuilder> 
        getCredFieldBuilder() {
      if (credBuilder_ == null) {
        credBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            drive_protocol.request.CredentialInfo, drive_protocol.request.CredentialInfo.Builder, drive_protocol.request.CredentialInfoOrBuilder>(
                getCred(),
                getParentForChildren(),
                isClean());
        cred_ = null;
      }
      return credBuilder_;
    }

    private int command_ = 0;
    /**
     * <code>.drive_protocol.request.SubMessage.Command command = 2;</code>
     * @return The enum numeric value on the wire for command.
     */
    @java.lang.Override public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.drive_protocol.request.SubMessage.Command command = 2;</code>
     * @param value The enum numeric value on the wire for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandValue(int value) {
      
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.drive_protocol.request.SubMessage.Command command = 2;</code>
     * @return The command.
     */
    @java.lang.Override
    public drive_protocol.request.SubMessage.Command getCommand() {
      @SuppressWarnings("deprecation")
      drive_protocol.request.SubMessage.Command result = drive_protocol.request.SubMessage.Command.valueOf(command_);
      return result == null ? drive_protocol.request.SubMessage.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>.drive_protocol.request.SubMessage.Command command = 2;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(drive_protocol.request.SubMessage.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.drive_protocol.request.SubMessage.Command command = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:drive_protocol.request.SubMessage)
  }

  // @@protoc_insertion_point(class_scope:drive_protocol.request.SubMessage)
  private static final drive_protocol.request.SubMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new drive_protocol.request.SubMessage();
  }

  public static drive_protocol.request.SubMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubMessage>
      PARSER = new com.google.protobuf.AbstractParser<SubMessage>() {
    @java.lang.Override
    public SubMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public drive_protocol.request.SubMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

