// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package drive_protocol.request;

public interface SubMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:drive_protocol.request.SubMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.drive_protocol.comm.Command command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  int getCommandValue();
  /**
   * <code>.drive_protocol.comm.Command command = 1;</code>
   * @return The command.
   */
  drive_protocol.Command getCommand();

  /**
   * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
   * @return Whether the connection field is set.
   */
  boolean hasConnection();
  /**
   * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
   * @return The connection.
   */
  drive_protocol.ConnectionInfo getConnection();
  /**
   * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
   */
  drive_protocol.ConnectionInfoOrBuilder getConnectionOrBuilder();
}
