// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package drive_protocol.request;

/**
 * Protobuf type {@code drive_protocol.request.SubMessage}
 */
public final class SubMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:drive_protocol.request.SubMessage)
    SubMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubMessage.newBuilder() to construct.
  private SubMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubMessage() {
    command_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SubMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          case 18: {
            drive_protocol.ConnectionInfo.Builder subBuilder = null;
            if (connection_ != null) {
              subBuilder = connection_.toBuilder();
            }
            connection_ = input.readMessage(drive_protocol.ConnectionInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(connection_);
              connection_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            drive_protocol.request.SubMessage.class, drive_protocol.request.SubMessage.Builder.class);
  }

  public static final int COMMAND_FIELD_NUMBER = 1;
  private int command_;
  /**
   * <code>.drive_protocol.comm.Command command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  @java.lang.Override public int getCommandValue() {
    return command_;
  }
  /**
   * <code>.drive_protocol.comm.Command command = 1;</code>
   * @return The command.
   */
  @java.lang.Override public drive_protocol.Command getCommand() {
    @SuppressWarnings("deprecation")
    drive_protocol.Command result = drive_protocol.Command.valueOf(command_);
    return result == null ? drive_protocol.Command.UNRECOGNIZED : result;
  }

  public static final int CONNECTION_FIELD_NUMBER = 2;
  private drive_protocol.ConnectionInfo connection_;
  /**
   * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
   * @return Whether the connection field is set.
   */
  @java.lang.Override
  public boolean hasConnection() {
    return connection_ != null;
  }
  /**
   * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
   * @return The connection.
   */
  @java.lang.Override
  public drive_protocol.ConnectionInfo getConnection() {
    return connection_ == null ? drive_protocol.ConnectionInfo.getDefaultInstance() : connection_;
  }
  /**
   * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
   */
  @java.lang.Override
  public drive_protocol.ConnectionInfoOrBuilder getConnectionOrBuilder() {
    return getConnection();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (command_ != drive_protocol.Command.Handshake.getNumber()) {
      output.writeEnum(1, command_);
    }
    if (connection_ != null) {
      output.writeMessage(2, getConnection());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (command_ != drive_protocol.Command.Handshake.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, command_);
    }
    if (connection_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getConnection());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof drive_protocol.request.SubMessage)) {
      return super.equals(obj);
    }
    drive_protocol.request.SubMessage other = (drive_protocol.request.SubMessage) obj;

    if (command_ != other.command_) return false;
    if (hasConnection() != other.hasConnection()) return false;
    if (hasConnection()) {
      if (!getConnection()
          .equals(other.getConnection())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    if (hasConnection()) {
      hash = (37 * hash) + CONNECTION_FIELD_NUMBER;
      hash = (53 * hash) + getConnection().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static drive_protocol.request.SubMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static drive_protocol.request.SubMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static drive_protocol.request.SubMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(drive_protocol.request.SubMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code drive_protocol.request.SubMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:drive_protocol.request.SubMessage)
      drive_protocol.request.SubMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              drive_protocol.request.SubMessage.class, drive_protocol.request.SubMessage.Builder.class);
    }

    // Construct using drive_protocol.request.SubMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      command_ = 0;

      if (connectionBuilder_ == null) {
        connection_ = null;
      } else {
        connection_ = null;
        connectionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return drive_protocol.request.Request.internal_static_drive_protocol_request_SubMessage_descriptor;
    }

    @java.lang.Override
    public drive_protocol.request.SubMessage getDefaultInstanceForType() {
      return drive_protocol.request.SubMessage.getDefaultInstance();
    }

    @java.lang.Override
    public drive_protocol.request.SubMessage build() {
      drive_protocol.request.SubMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public drive_protocol.request.SubMessage buildPartial() {
      drive_protocol.request.SubMessage result = new drive_protocol.request.SubMessage(this);
      result.command_ = command_;
      if (connectionBuilder_ == null) {
        result.connection_ = connection_;
      } else {
        result.connection_ = connectionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof drive_protocol.request.SubMessage) {
        return mergeFrom((drive_protocol.request.SubMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(drive_protocol.request.SubMessage other) {
      if (other == drive_protocol.request.SubMessage.getDefaultInstance()) return this;
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      if (other.hasConnection()) {
        mergeConnection(other.getConnection());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      drive_protocol.request.SubMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (drive_protocol.request.SubMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int command_ = 0;
    /**
     * <code>.drive_protocol.comm.Command command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    @java.lang.Override public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.drive_protocol.comm.Command command = 1;</code>
     * @param value The enum numeric value on the wire for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandValue(int value) {
      
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.drive_protocol.comm.Command command = 1;</code>
     * @return The command.
     */
    @java.lang.Override
    public drive_protocol.Command getCommand() {
      @SuppressWarnings("deprecation")
      drive_protocol.Command result = drive_protocol.Command.valueOf(command_);
      return result == null ? drive_protocol.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>.drive_protocol.comm.Command command = 1;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(drive_protocol.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.drive_protocol.comm.Command command = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }

    private drive_protocol.ConnectionInfo connection_;
    private com.google.protobuf.SingleFieldBuilderV3<
        drive_protocol.ConnectionInfo, drive_protocol.ConnectionInfo.Builder, drive_protocol.ConnectionInfoOrBuilder> connectionBuilder_;
    /**
     * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
     * @return Whether the connection field is set.
     */
    public boolean hasConnection() {
      return connectionBuilder_ != null || connection_ != null;
    }
    /**
     * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
     * @return The connection.
     */
    public drive_protocol.ConnectionInfo getConnection() {
      if (connectionBuilder_ == null) {
        return connection_ == null ? drive_protocol.ConnectionInfo.getDefaultInstance() : connection_;
      } else {
        return connectionBuilder_.getMessage();
      }
    }
    /**
     * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
     */
    public Builder setConnection(drive_protocol.ConnectionInfo value) {
      if (connectionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        connection_ = value;
        onChanged();
      } else {
        connectionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
     */
    public Builder setConnection(
        drive_protocol.ConnectionInfo.Builder builderForValue) {
      if (connectionBuilder_ == null) {
        connection_ = builderForValue.build();
        onChanged();
      } else {
        connectionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
     */
    public Builder mergeConnection(drive_protocol.ConnectionInfo value) {
      if (connectionBuilder_ == null) {
        if (connection_ != null) {
          connection_ =
            drive_protocol.ConnectionInfo.newBuilder(connection_).mergeFrom(value).buildPartial();
        } else {
          connection_ = value;
        }
        onChanged();
      } else {
        connectionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
     */
    public Builder clearConnection() {
      if (connectionBuilder_ == null) {
        connection_ = null;
        onChanged();
      } else {
        connection_ = null;
        connectionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
     */
    public drive_protocol.ConnectionInfo.Builder getConnectionBuilder() {
      
      onChanged();
      return getConnectionFieldBuilder().getBuilder();
    }
    /**
     * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
     */
    public drive_protocol.ConnectionInfoOrBuilder getConnectionOrBuilder() {
      if (connectionBuilder_ != null) {
        return connectionBuilder_.getMessageOrBuilder();
      } else {
        return connection_ == null ?
            drive_protocol.ConnectionInfo.getDefaultInstance() : connection_;
      }
    }
    /**
     * <code>.drive_protocol.comm.ConnectionInfo connection = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        drive_protocol.ConnectionInfo, drive_protocol.ConnectionInfo.Builder, drive_protocol.ConnectionInfoOrBuilder> 
        getConnectionFieldBuilder() {
      if (connectionBuilder_ == null) {
        connectionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            drive_protocol.ConnectionInfo, drive_protocol.ConnectionInfo.Builder, drive_protocol.ConnectionInfoOrBuilder>(
                getConnection(),
                getParentForChildren(),
                isClean());
        connection_ = null;
      }
      return connectionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:drive_protocol.request.SubMessage)
  }

  // @@protoc_insertion_point(class_scope:drive_protocol.request.SubMessage)
  private static final drive_protocol.request.SubMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new drive_protocol.request.SubMessage();
  }

  public static drive_protocol.request.SubMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubMessage>
      PARSER = new com.google.protobuf.AbstractParser<SubMessage>() {
    @java.lang.Override
    public SubMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public drive_protocol.request.SubMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

