// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package drive_protocol.request;

public interface SubMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:drive_protocol.request.SubMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
   * @return Whether the cred field is set.
   */
  boolean hasCred();
  /**
   * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
   * @return The cred.
   */
  drive_protocol.request.CredentialInfo getCred();
  /**
   * <code>.drive_protocol.request.CredentialInfo cred = 1;</code>
   */
  drive_protocol.request.CredentialInfoOrBuilder getCredOrBuilder();

  /**
   * <code>.drive_protocol.request.SubMessage.Command command = 2;</code>
   * @return The enum numeric value on the wire for command.
   */
  int getCommandValue();
  /**
   * <code>.drive_protocol.request.SubMessage.Command command = 2;</code>
   * @return The command.
   */
  drive_protocol.request.SubMessage.Command getCommand();
}
