// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package drive_protocol.response;

public interface GetFileInformationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:drive_protocol.response.GetFileInformationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>uint64 file_attributes = 2;</code>
   * @return The fileAttributes.
   */
  long getFileAttributes();
}
