// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package drive_protocol.response;

public interface GetFileInformationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:drive_protocol.response.GetFileInformationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>uint64 file_attributes = 2;</code>
   * @return The fileAttributes.
   */
  long getFileAttributes();

  /**
   * <code>int64 file_creation_time = 3;</code>
   * @return The fileCreationTime.
   */
  long getFileCreationTime();

  /**
   * <code>int64 file_last_access_time = 4;</code>
   * @return The fileLastAccessTime.
   */
  long getFileLastAccessTime();

  /**
   * <code>int64 file_last_write_time = 5;</code>
   * @return The fileLastWriteTime.
   */
  long getFileLastWriteTime();

  /**
   * <code>uint64 file_size = 6;</code>
   * @return The fileSize.
   */
  long getFileSize();
}
