// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package drive_protocol.response;

public interface PubMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:drive_protocol.response.PubMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.drive_protocol.response.PubMessage.Command command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  int getCommandValue();
  /**
   * <code>.drive_protocol.response.PubMessage.Command command = 1;</code>
   * @return The command.
   */
  drive_protocol.response.PubMessage.Command getCommand();
}
