// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package drive_protocol.response;

public interface ReadFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:drive_protocol.response.ReadFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>bytes buffer = 2;</code>
   * @return The buffer.
   */
  com.google.protobuf.ByteString getBuffer();
}
