// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package drive_protocol.response;

public interface SetEndOfFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:drive_protocol.response.SetEndOfFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();
}
